name: Load Testing Workflow

on:
  schedule:
  - cron: "0 0 1 */3 *"
  
  push:
    branches:
      - main

jobs:
  load_test:
    runs-on: 
      ubuntu-latest
    steps:
      # checkout the code from the repo
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install Dependencies
      - name: Install Dependencies
        uses: pip install -r requirements.txt

      # Run Load Test using locust with specified parameters
      - name: Run Load Test
        run: locust -f ../../load_test.py --headless --user=50 --spawn-rate=10 --host https://jsonplaceholder.typicode.com --run-time=4s