name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Repository Checking 
        uses: actions/checkout@v2
      # Set up the version of Python to be used
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Install the dependencies for the project
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_add.txt
      # Run the Test Suite for the Project
      - name: Run Tests
        run: python -m pytest